config/routes.rb
ACMDB::Application.routes.draw do
  resources :machines

  devise_for :users
  resources :jobs

  get "welcome/index"

  root to: 'welcome#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :name, :job_type, :box_name, :owner, :command, :machine, :permission, :date_condition, 
                  :days_of_week, :start_times, :condition, :short_description, :str_out_file, :str_err_file, 
                  :alarm_if_fail, :avg_runtime_min, :avg_runtime_sec, :max_runtime_min, :contacts, :system, 
                  :system_type, :description, :priority, :critical, :actions, :notes, :submited_by, :created_on, 
                  :modified_by, :last_modified_on, :update_log, :status, :machine_id
                  
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_inclusion_of :job_type, :in => %w(c b f), :message => "%{value} is not a valid job type. Needs to be a Job (j), Box (b) or Filewatcher (f)."
  validates_format_of :owner, :with => /\A[A-Z0-9._%+-]+@BKGLOBAL\z/i
  #validates_numericality_of :date_condition, :only_integer => true, :message => "can only be a number 0 or 1."
  #validates_inclusion_of :date_condition, :in => 0..1, :message => "can only be 0 or 1." 
  #validates_numericality_of :alarm_if_fail, :only_integer => true, :message => "can only be a number 0 or 1."
  #validates_inclusion_of :alarm_if_fail, :in => 0..1, :message => "can only be 0 or 1." 
  #validates_numericality_of :avg_runtime_min, :message => "can only be a number. Time is in minutes."
  #validates_numericality_of :avg_runtime_sec, :message => "can only be a number. Time is in seconds."
  #validates_numericality_of :max_runtime_min, :message => "can only be a number. Time is in minutes."


  belongs_to :machine
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  attr_accessible :name, :server_name, :status, :ip, :os, :environment, :hosting, :hoster, :system, :system_type, :backup_server
  
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_format_of :ip, :with => /\A\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\z/i
  
  has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @job_types = ['Job', 'Box', 'Filewatchet']
  end

  # GET /jobs/1/edit
  def edit
    @job_types = ['Job', 'Box', 'Filewatchet']
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :job_type, :box_name, :owner, :command, :machine, :permission, :date_condition, :days_of_week, :start_times, :condition, :short_description, :str_out_file, :str_err_file, :alarm_if_fail, :avg_runtime_min, :avg_runtime_sec, :max_runtime_min, :contacts, :system, :system_type, :description, :priority, :critical, :actions, :notes, :submited_by, :created_on, :modified_by, :last_modified_on, :update_log, :status)
    end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render action: 'show', status: :created, location: @machine }
      else
        format.html { render action: 'new' }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:name, :server_name, :status, :ip, :os, :environment, :hosting, :hoster, :system, :system_type, :backup_server)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :job_type, collection: @job_types %>
  <%= f.input :box_name %>
  <%= f.input :owner, placeholder: 'bkpbtch@bkglobal' %>
  <%= f.input :command %>
  <%= f.association :machine %>
  <%= f.input :permission %>
  <%= f.input :date_condition %>
  <%= f.input :days_of_week %>
  <%= f.input :start_times %>
  <%= f.input :condition %>
  <%= f.input :short_description %>
  <%= f.input :str_out_file, label: 'Standard Output File' %>
  <%= f.input :str_err_file, label: 'Standard Error File' %>
  <%= f.input :alarm_if_fail, placeholder: '1' %>
  <%= f.input :avg_runtime_min, label: 'Average Runtime (Minutes)' %>
  <%= f.input :avg_runtime_sec, label: 'Average Runtime (Seconds)' %>
  <%= f.input :max_runtime_min, label: 'Maximum Runtime (Minutes)' %>
  <%= f.input :contacts %>
  <%= f.input :system %>
  <%= f.input :system_type %>
  <%= f.input :description %>
  <%= f.input :priority %>
  <%= f.input :critical %>
  <%= f.input :actions %>
  <%= f.input :notes %>
  <%= f.input :submited_by %>
  <%= f.input :created_on %>
  <%= f.input :modified_by %>
  <%= f.input :last_modified_on %>
  <%= f.input :update_log %>
  <%= f.input :status %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                jobs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped datatable">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:system) %></th>
      <th><%= model_class.human_attribute_name(:system_type) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.box_name + " / " if (job.job_type == 'c') and (job.box_name != '') %><%= link_to job.name, job_path(job) %></td>
        <td><%= job.system %></td>
        <td><%= job.system_type %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %>

app/views/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/show.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @job.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:job_type) %>:</strong></dt>
  <dd><%= @job.job_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:box_name) %>:</strong></dt>
  <dd><%= @job.box_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:owner) %>:</strong></dt>
  <dd><%= @job.owner %></dd>
  <dt><strong><%= model_class.human_attribute_name(:command) %>:</strong></dt>
  <dd><%= @job.command %></dd>
  <dt><strong><%= model_class.human_attribute_name(:machine) %>:</strong></dt>
  <dd><%= @job.machine ? @job.machine.name+" ("+@job.machine.ip+")" : "None" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:permission) %>:</strong></dt>
  <dd><%= @job.permission %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_condition) %>:</strong></dt>
  <dd><%= @job.date_condition %></dd>
  <dt><strong><%= model_class.human_attribute_name(:days_of_week) %>:</strong></dt>
  <dd><%= @job.days_of_week %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_times) %>:</strong></dt>
  <dd><%= @job.start_times %></dd>
  <dt><strong><%= model_class.human_attribute_name(:condition) %>:</strong></dt>
  <dd><%= @job.condition %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_description) %>:</strong></dt>
  <dd><%= @job.short_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:str_out_file) %>:</strong></dt>
  <dd><%= @job.str_out_file %></dd>
  <dt><strong><%= model_class.human_attribute_name(:str_err_file) %>:</strong></dt>
  <dd><%= @job.str_err_file %></dd>
  <dt><strong><%= model_class.human_attribute_name(:alarm_if_fail) %>:</strong></dt>
  <dd><%= @job.alarm_if_fail %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avg_runtime_min) %>:</strong></dt>
  <dd><%= @job.avg_runtime_min %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avg_runtime_sec) %>:</strong></dt>
  <dd><%= @job.avg_runtime_sec %></dd>
  <dt><strong><%= model_class.human_attribute_name(:max_runtime_min) %>:</strong></dt>
  <dd><%= @job.max_runtime_min %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contacts) %>:</strong></dt>
  <dd><%= @job.contacts %></dd>
  <dt><strong><%= model_class.human_attribute_name(:system) %>:</strong></dt>
  <dd><%= @job.system %></dd>
  <dt><strong><%= model_class.human_attribute_name(:system_type) %>:</strong></dt>
  <dd><%= @job.system_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @job.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:priority) %>:</strong></dt>
  <dd><%= @job.priority %></dd>
  <dt><strong><%= model_class.human_attribute_name(:critical) %>:</strong></dt>
  <dd><%= @job.critical %></dd>
  <dt><strong><%= model_class.human_attribute_name(:actions) %>:</strong></dt>
  <dd><%= @job.actions %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @job.notes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:submited_by) %>:</strong></dt>
  <dd><%= @job.submited_by %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_on) %>:</strong></dt>
  <dd><%= @job.created_on %></dd>
  <dt><strong><%= model_class.human_attribute_name(:modified_by) %>:</strong></dt>
  <dd><%= @job.modified_by %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_modified_on) %>:</strong></dt>
  <dd><%= @job.last_modified_on %></dd>
  <dt><strong><%= model_class.human_attribute_name(:update_log) %>:</strong></dt>
  <dd><%= @job.update_log %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @job.status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              jobs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_path(@job), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              job_path(@job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>

<%= link_to "Home", root_path, :class => 'brand' %>
<div class="nav-collapse collapse">
	<ul class="nav">
	  <li class="divider-vertical"></li>
	  <li><%= link_to "Jobs", jobs_path %></li>
	  <li class="divider-vertical"></li>
	  <li><%= link_to "Machines", machines_path %></li>
	  <li class="divider-vertical"></li>
	  <% if user_signed_in? %>
	    <li>
	    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
	    </li>
	  <% else %>
	    <li>
	    <%= link_to('Login', new_user_session_path)  %>
	    </li>
	  <% end %>
	  <li class="divider-vertical"></li>
	  <% if user_signed_in? %>
	    <li>
	    <%= link_to('Edit account', edit_user_registration_path) %>
	    </li>
	  <% else %>
	    <li>
	    <%= link_to('Sign up', new_user_registration_path)  %>
	    </li>
	  <% end %>
	  <li class="divider-vertical"></li>
	</ul>
	<form class="navbar-search pull-left">
	  <input type="text" class="search-query" placeholder="Search">
	</form>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ACMDB" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/machines/_form.html.erb
<%= simple_form_for @machine, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :server_name %>
  <%= f.input :status %>
  <%= f.input :ip %>
  <%= f.input :os %>
  <%= f.input :environment %>
  <%= f.input :hosting %>
  <%= f.input :hoster %>
  <%= f.input :system %>
  <%= f.input :system_type %>
  <%= f.input :backup_server %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                machines_path, :class => 'btn' %>
  </div>
<% end %>

app/views/machines/edit.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/index.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped datatable">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:server_name) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:ip) %></th>
      <th><%= model_class.human_attribute_name(:os) %></th>
      <th><%= model_class.human_attribute_name(:environment) %></th>
      <th><%= model_class.human_attribute_name(:system) %></th>
      <th>Type</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= link_to machine.name, machine_path(machine) %></td>
        <td><%= machine.server_name %></td>
        <td><%= machine.status %></td>
        <td><%= machine.ip %></td>
        <td><%= machine.os %></td>
        <td><%= machine.environment %></td>
        <td><%= machine.system %></td>
        <td><%= machine.system_type %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_machine_path(machine), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      machine_path(machine),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_machine_path,
            :class => 'btn btn-primary' %>

app/views/machines/new.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/show.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @machine.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server_name) %>:</strong></dt>
  <dd><%= @machine.server_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @machine.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ip) %>:</strong></dt>
  <dd><%= @machine.ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:os) %>:</strong></dt>
  <dd><%= @machine.os %></dd>
  <dt><strong><%= model_class.human_attribute_name(:environment) %>:</strong></dt>
  <dd><%= @machine.environment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hosting) %>:</strong></dt>
  <dd><%= @machine.hosting %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hoster) %>:</strong></dt>
  <dd><%= @machine.hoster %></dd>
  <dt><strong><%= model_class.human_attribute_name(:system) %>:</strong></dt>
  <dd><%= @machine.system %></dd>
  <dt><strong><%= model_class.human_attribute_name(:system_type) %>:</strong></dt>
  <dd><%= @machine.system_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:backup_server) %>:</strong></dt>
  <dd><%= @machine.backup_server %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              machines_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_machine_path(@machine), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              machine_path(@machine),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/welcome/index.html.erb
<h1>Autosys Configuration Management Database</h1>
<div>
 <%= link_to "Jobs", jobs_path %></br>
 <%= link_to "Machines", machines_path %>
</div>